package:
  name: pypotrace
  version: 0.1.3

source:
  url: https://pypi.python.org/packages/28/6f/59ebf9fa50553426d28c0aec6d0690e84cca3841edd10276afaaedb8d02b/pypotrace-0.1.3.tar.gz
  fn: pypotrace-0.1.3.tar.gz
  md5: ca6620cd56f41464ac12a970cdf89391
requirements:
  build:
    - gcc 4.8.5
    - python 2.7.13
    - numpy 1.12.0 py27_blas_openblas_200
    - libagg 2.5.0
    - potrace 1.11
  run:
    - python 2.7.13
    - numpy 1.12.0 py27_blas_openblas_200
    - libagg 2.5.0
    - potrace 1.11

build:
  string: py{{py}}_0

about:
  home: https://github.com/flupke/pypotrace
  summary: "These bindings provide an object oriented API to the potrace library."
  license: GPL
