package:
  name: validators
  version: "0.11.0"

source:
  fn: validators-0.11.0.tar.gz
  url: https://pypi.python.org/packages/b8/a7/e83349927b2e38e8b066cfd1f7ee538e9fe77a7cc0fe1bda70244a1f0ce7/validators-0.11.0.tar.gz
  md5: db91d2c453c3b1269be0f186635319a6

build:
  number: 0
  skip: False

requirements:
  build:
    - python 2.7.13
    - setuptools 39.2.0
    - six 1.10.0
    - decorator 4.0.10

  run:
    - python 2.7.13
    - six 1.10.0
    - decorator 4.0.10

test:
  imports:
    - validators
    - validators.i18n

about:
  home: https://github.com/kvesteri/validators
  license: BSD License
  summary: 'Python Data Validation for Humans.'
