package:
  name: intervals
  version: "0.8.0"

source:
  fn: intervals-0.8.0.tar.gz
  url: https://pypi.python.org/packages/30/7a/7364356d073426b73014bc6f7aab36914fd9fc53e8d99150a0de69d7846a/intervals-0.8.0.tar.gz
  md5: d2e7b132a4a00f001938cf47884b5e60

build:
  skip: False
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - infinity 1.4

  run:
    - python
    - infinity 1.4

test:
  imports:
    - intervals

about:
  home: https://github.com/kvesteri/intervals
  license: BSD License
  summary: 'Python tools for handling intervals (ranges of comparable objects).'
